name: Release to WordPress.org repository

on:
  release:
    types: [released]

jobs:
  deploy_to_wp_repository:
    name: Deploy to WP.org
      runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Composer install
          uses: php-actions/composer@v6
        - name: Push to WordPress repository
          uses: 10up/action-wordpress-plugin-deploy@stable
          env:
            SLUG: miso-ai
            SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
            SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
